--- 
name: "NavSimple"
description: "Simple form validation with good UX"
category: "Interface"
tags: 
  - "navigation"
current: "0.1"
author: "3n"
contact: "ian.collins@gmail.com"
website: "http://www.iancollins.me"
demo: "https://www.banksimple.com"
sources:
  - "Source/NavSimple.js"